[package]
name = "steam-dlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = ["derive"] }
color-eyre = "0.6.2"

[profile.release]
lto = true
codegen-units = 1
